# Generated by Django 3.2.8 on 2022-04-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_achievements_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='certificate',
        ),
    ]
