# Generated by Django 3.2.8 on 2022-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_remove_achievements_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='certificate',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
