# Generated by Django 3.2.8 on 2022-04-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_alter_achievements_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='certificate',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterOrderWithRespectTo(
            name='achievements',
            order_with_respect_to='user',
        ),
    ]
