# Generated by Django 3.2.8 on 2022-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_auto_20220411_1929'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='achievements',
            order_with_respect_to=None,
        ),
    ]
