# Generated by Django 3.2.8 on 2022-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_alter_achievements_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='roll_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
