# Generated by Django 3.2.8 on 2022-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_auto_20220429_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
