# Generated by Django 3.2.8 on 2022-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_profile_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fname',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
